### ISSUE TITLE
Mod did not save Config changes 

### ISSUE THREAD

**Issue by Luxley** [Siphalor/spiceoffabric#1]
Hi siphalor.

I tried changing values in the config through clientside Mod Menu. Saved the values and then closed the game to transfer the mod .jar and config to server. 

None of the changes where retained, both client and server.

**Comment by Siphalor** [comment]
Should be fixed with the latest commit.
Please reopen if it bugs out again ;)

**Comment by Luxley** [comment]
@Siphalor 
I dont know how to reopen the ticket aside from just making a new post but im still having the same issue.

**Comment by Siphalor** [comment]
hm

**Comment by Siphalor** [comment]
Are you an operator on the server?

**Comment by Luxley** [comment]
@Siphalor yep!
